apiVersion: apps/v1
kind: Deployment
metadata:
  name: gembook-svc-deployment
  namespace: dev
  labels:
    app: gembook-svc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gembook-svc
  template:
    metadata:
      labels:
        app: gembook-svc
    spec:
      containers:
      - name: gembook-svc
        image: 543223517360.dkr.ecr.ap-south-1.amazonaws.com/dockercreds:latest
        # envFrom:
        # - secretRef:
        #     name: secret-gembook-db
        # - secretRef:
        #     name: secret-gembook-s3
        ports:
        - name: gembook
          containerPort: 80
        imagePullPolicy: Always
